services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: EnterpriseApp
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: password
    ports:
      - "443:80"
    depends_on:
      - mysql

volumes:
  mysqldata:
